# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-09 09:20
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uuid', models.CharField(blank=True, help_text='用户uuid', max_length=50, null=True, unique=True)),
                ('user_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cellphone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('real_name', models.CharField(blank=True, max_length=20, null=True)),
                ('id_card', models.CharField(blank=True, max_length=50, null=True)),
                ('wechat_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('wechat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alipay_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('alipay_name', models.CharField(blank=True, max_length=100, null=True)),
                ('authentic', models.CharField(choices=[('0', 'CA个人扫脸认证'), ('1', 'CA银联卡认证'), ('2', 'CA企业认证'), ('3', '支付宝认证'), ('4', '管理员验证'), ('5', '未认证'), ('33', '绑定支付宝')], default='5', max_length=10)),
                ('authentic_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('0', '个人用户'), ('1', '企业用户-法人'), ('2', '管理员'), ('3', '企业用户-非法人')], default='0', max_length=10)),
                ('status', models.CharField(choices=[('0', '未认证'), ('1', '已认证[中]'), ('2', '已认证[高]'), ('3', '认证中'), ('4', '认证失败')], default='0', max_length=10)),
                ('version_number', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
