# Generated by Django 3.0.1 on 2021-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64)),
                ('dem_id', models.CharField(max_length=12)),
                ('sup_id', models.CharField(max_length=12)),
                ('code', models.CharField(max_length=12)),
                ('msg', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_log',
            },
        ),
        migrations.CreateModel(
            name='JobStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64)),
                ('dem_id', models.CharField(max_length=12)),
                ('sup_id', models.CharField(max_length=12)),
                ('avg_cost', models.IntegerField()),
                ('sum_use', models.IntegerField()),
                ('success_rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_statistics',
            },
        ),
        migrations.CreateModel(
            name='JobStatisticsLatest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_time', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.CharField(max_length=64)),
                ('dem_id', models.CharField(max_length=12)),
                ('sup_id', models.CharField(max_length=12)),
                ('avg_cost', models.IntegerField()),
                ('sum_use', models.IntegerField()),
                ('success_rate', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_statistics_latest',
            },
        ),
    ]
